routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/inicio', function () {
  //  return view('layouts.menu');
//});


Route::get('/home/', 'HomeController@index')->name('home');
//USUARIOS CRUD
Route::get('/users/','UsersController@users')->name('users');
Route::get('/inmuebles/','InmuebleController@inmuebles')->name('inmuebles');
Route::get('/clientes/','ClienteController@clientes')->name('clientes');
Route::get('/demandas/','DemandaController@demandas')->name('demandas');
Route::get('/reportes/','ReporteController@demandas')->name('reportes');

//Nav-Bar
Route::resource('inmuebles','InmuebleController');
Route::resource('clientes','ClienteController');
Route::resource('pais','PaiController');
Route::resource('ciudades','CiudadeController');
Route::resource('pagos','PagosController');
Route::resource('demandas','DemandaController');
Route::resource('caracteristicas','CaracteristicaController');
Route::resource('reporte','ReporteController');
Route::resource('corredores','CorredoreController');
Route::resource('users','UsersController');



// GOOGLE MAPAS USO
//Route::get('/ciudades','CiudadesController@mapa');
//Route::get('/', function() { 
//	$config=array(); 
//	$config['center']='New York, USA';
//	GMaps::initialize($config); 
//	$ciudades=GMaps::create_map();                    
//    echo $ciudades['js'];
//	echo $ciudades['html']; 
//}); 

//Route::get('googlemap', 'CiudadesController@mapa');
//Route::get('googlemap/direction', 'MapController@direction');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id','name', 'email','password','updated_at','created_at','nombre_usuario','apellido','ciudad','celular',  'telefono',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
   
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Session;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(10);
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max: 255',
            'apellido' => 'required|max: 255',
            'email' => 'required',
            'password' => 'required',
            'ciudad' => 'required|in:la_paz,cbba,stcz,oruro,potosi,sucre,tarija,beni,pando',                     
            'nombre_usuario' => 'required|max: 255',
            'celular' => 'required',
            'telefono' => 'required',
        ]);

        //dd($request->all());

        User::create(
        ['name'=> $request->name,
        'apellido'=> $request->apellido,
        'email'=> $request->email,
        'password'=> $request->password,
        'ciudad'=> $request->ciudad,
        'nombre_usuario'=> $request->nombre_usuario,       
        'celular'=> $request->celular,
        'telefono'=> $request->telefono,
        
        ]);

        Session::flash('message','Usuario creado exisitosamente');
        return redirect()->route('users.index');  
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pai  $pai
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
         return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pai  $pai
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pai  $pai
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pai  $pai
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }

     public function users(){
       return view('users');
    }
}

resources/views/users/create.blade.php
@extends('layouts.admin')
@section('cont')
<div class="container">
  <div class="panel panel-success" style="padding: 1vh;border-radius: 9px;">
    <div class="form-group">
      @if($errors->any())
        <div class="alert alert-danger">
          <p style="color:green;">Formulario no completado! <br>Porfavor rellene todos los campos</p>
          <ul>
            @foreach($errors->all() as $error)
            <li>{{$error}}</li>
            @endforeach
          </ul>
        </div>
        @endif
      <form action="{{route('users.store')}}" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
        @csrf  <!-- token de proteccion -->
        @if (session('status'))
        @csrf_filed()
        <div class="alert alert-success">
          {{ session('status') }}
        </div>
        @endif
        <div class="row">
          <div class="col-6"><span style="color:green;">Registro Usuario</span>         
          <div class="form-group">
            <label>{{ __('Name') }}</label>
            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
            @error('name')
            <span class="invalid-feedback" role="alert">
              <strong>{{ $message }}</strong>
            </span>
            @enderror
          </div>
          <label>Apellidos:</label>
          <input type="text" class="form-control" name="apellido">
          <br>
          <div class="form-group">
            <label for="email" >{{ __('E-Mail Address') }}</label>
            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">
            @error('email')
            <span class="invalid-feedback" role="alert">
              <strong>{{ $message }}</strong>
            </span>
            @enderror
          </div>
          <div class="form-group">
            <label for="password" >{{ __('Password') }}</label>
            <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">
            @error('password')
            <span class="invalid-feedback" role="alert">
              <strong>{{ $message }}</strong>
            </span>
            @enderror
          </div>
          <div class="form-group">
            <label for="password-confirm" >{{ __('Confirm Password') }}</label>
            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
          </div>
          
        </div>
        <div class="col-6">
          <br>
          <div class="form-group">Ciudad
            <select  name="ciudad" id="ciudad" class="form-control">
              <option >Elija Ciudad</option>
              <option value="la_paz">La Paz</option>
              <option value="cbba">Cochabamba</option>
              <option value="stcz">Santa Cruz</option>
              <option value="oruro">Oruro</option>
              <option value="potosi">Potosi</option>
              <option value="sucre">Sucre</option>
              <option value="tarija">Tarija</option>
              <option value="pando">Pando</option>
              <option value="beni">Beni</option>
            </select>
          </div>
          <br>
          <label>Nombre Usuario:</label>
          <input type="text" class="form-control" name="nombre_usuario">
          <br>
          <label>Celular:</label>
          <input type="text" class="form-control" name="celular">
          <br>
          <label>Telefono:</label>
          <input type="text" class="form-control" name="telefono">
          <br>
          <label>Imagen Usuario:</label>
          <br>
          <input name="imagen_perfil" type="file" />
          <div class="col-md-12 text-right">
            <button type="submit" class="btn btn-primary" onclick="return confirm('¿Desea guardar el registro?')">Guardar</button>
            <a href="{{route('users.index')}}" type="button" class="btn btn-outline-dark" style="cursor: grab;">Atras</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
</div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('content')
<!DOCTYPE html>
<html lang="en">
  <body>
    <div class="container">
      <a href="{{route('usuarios.index')}}" type="button" class="btn btn-outline-dark mb-3" style="cursor: grab;">Atras</a>
      <div class="panel-group mb-3"><div class="panel-heading">Registro Usuarios Pro Viviendas
      </div>
      <div class="panel panel-success" style="background: gainsboro; padding: 1vh;border-radius: 9px;">
        <div class="form-group">

          <form action="{{route('usuarios.update', $usuarios->id_usuario)}}" >
            @csrf
            @method('PUT')

            <label for="usr">Nombre:</label>
            <input type="text" class="form-control" id="usr" name="nombre" data-msg="Por favor seleccione el plan que desee" value="{{$usuarios->nombre}}">
            <br>
            <label for="usr">Apellido:</label>
            <input type="text" class="form-control" name="apellido" value="{{$usuarios->apellido}}">
            <br>
            <div class="form-group">Ciudad
              <select  name="tipo" id="tipo" type="text"  class="form-control" name="ciudad" data-msg="Por favor   seleccione el plan que desee">                
                <option >Elija una Ciudad</option>
                <option value="LP">La Paz</option>
                <option value="CBBA">Cochabamba</option>
                <option value="STCZ">Santa Cruz</option>  
              </select>
            </div>
            
            <label for="usr">Nombre de Usuario:</label>
            <input type="text" class="form-control" name="nombre_usuario" value="{{$usuarios->nombre-usuario}}">
            <br>
            <label for="usr">Celular:</label>
            <input type="text" class="form-control" name="celular" value="{{$usuarios->celular}}">
            <br>
            <label for="usr">Telefono:</label>
            <input type="text" class="form-control" name="telefono" value="{{$usuarios->telefono}}">
            <br>
            <label for="usr">Correo:</label>
            <input type="text" class="form-control" name="correo" value="{{$usuarios->correo}}">
            <br>
            <div class="form-group">Rol
              <select  name="tipo" id="tipo" type="text"  class="form-control" name="ciudad" data-msg="Por favor seleccione el plan que desee" >                
                <option>Elija Rol</option>
                <option value="root">Root</option>
                <option value="usuario">Usuario</option>
              </select>
              </div>
            <label for="usr">Imagen Perfil:</label>
            <br>
            <input name="imgperfil" type="file" />

            <div class="col-md-12 text-right">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
@endsection

resources/views/users/index.blade.php
@extends('layouts.admin')
@section('cont')
    <div class="card">
      <div class="container">
        <br>
        <h2 style="color:green;text-align: center;">Usuarios</h2>
        <div class="card-header" style="text-align: left;"><a href="{{route('users.create')}}" type="button" class="btn btn-info mb-3" style=" cursor: grab;border-radius: 5px; border: 1px green solid;">Agregar Usuario</a>
        <form method="GET"  accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
          <div class="input-group">
            <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
            <span class="input-group-append">
              <button class="btn btn-secondary" type="submit">
              <i class="fa fa-search"></i>
              </button>
            </span>
          </div>
        </form>
        @if (Session::has('message'))
        <div class="alert alert-info" style="color: green;background-color: darkseagreen;">{{ Session::get('message') }}</div>
        @endif
      </div>
      <div class="table-responsive-xl">
        <table class="table table-striped">
          <thead class="tabla">
            <tr>
               <th scope="col">IdUsuario</th>
          <th scope="col">Nombre</th>
          <th scope="col">Apellido</th>
          <th scope="col">Nombre Usuario</th>
          <th scope="col">Ciudad</th>
          <th scope="col"> Acciones</th>

            </tr>
          </thead>
          <tbody>
            @foreach($users as $user)
        <tr>
            <tr>
              <td>{{$user->id}}</td>
          <td>{{$user->name}}</td>
          <td>{{$user->email}}</td> 
          <td>{{$user->nombre_usuario}}</td>
          <td>{{$user->ciudad}}</td>
          
              <td>
                <!--VIEWS-->
                <a title="View Image" href="{{ route('users.show',$user->id ) }}"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i>Ver</button></a>
                <!--EDITAR-->
                <a title="Edit Image" href="{{ route('users.edit',$user->id ) }}"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar</button></a>
                <!--DELETE-->
                <form method="POST" accept-charset="UTF-8" style="display:inline">
                  <button href="{{ route('users.destroy',$user->id ) }}" type="submit" class="btn btn-danger btn-sm" title="Delete Image" onclick="return confirm(&quot;¿Desea eliminar?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Eliminar</button>
                </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
        {{$users->links()}}
        
      </div>
    </div>
  </div>
@endsection
<style type="text/css" media="screen">
.tabla{
color: green;
border-color: green;
}
</style>

resources/views/users/show.blade.php
@extends('layouts.admin')
@section('cont')
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<style>
/* Make the image fully responsive */
.carousel-inner img {
width: 50%;
height: 50%;
}
</style>
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card" style="width: 23rem;border: 2px solid green;border-radius: 5px;">
        <a href="{{route('users.index')}}" type="button" class="btn btn-outline-dark" style="cursor: grab;">Atras</a>
        
        <div id="demo" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          
          
          <!-- The slideshow -->
          <img src="..." class="card-img-top">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <h5 class="card-title">Nombre: {{$user->name}}</h5>
              <p class="card-text"><li class="list-group-item">Nombre Usuario:{{$user->nombre_usuario}} </li></p>
            </div>
          </div>
          <div class="card-body">
            
            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#demo" data-slide="prev">
              <span style="background-color: green;" class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo" data-slide="next">
              <span style="background-color: green;" class="carousel-control-next-icon"></span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="col">
      <ul class="list-group list-group-flush" style="border: 2px solid green;border-radius: 5px;">
        <li class="list-group-item">Id: {{$user->id}}</li>
        <li class="list-group-item">Apellido: {{$user->apellido}}</li>
        <li class="list-group-item">Email: {{$user->email}}</li>
        <li class="list-group-item">Ciudad: {{$user->ciudad}}</li>
        <li class="list-group-item">Celular: {{$user->celular}} </li>
        <li class="list-group-item">Teléfono: {{$user->telefono}}</li>
      </ul>
    </div>
  </div>
  
</div>
@endsection
<!-- <div class="card-body">
  <a href="#" class="card-link">Card link</a>
  <a href="#" class="card-link">Another link</a>
</div> -->