routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/inicio', function () {
  //  return view('layouts.menu');
//});


Route::get('/home/', 'HomeController@index')->name('home');
//USUARIOS CRUD
Route::get('/users/','UsersController@users')->name('users');
Route::get('/inmuebles/','InmuebleController@inmuebles')->name('inmuebles');
Route::get('/clientes/','ClienteController@clientes')->name('clientes');
Route::get('/demandas/','DemandaController@demandas')->name('demandas');
Route::get('/reportes/','ReporteController@demandas')->name('reportes');

//Nav-Bar
Route::resource('inmuebles','InmuebleController');
Route::resource('clientes','ClienteController');
Route::resource('pais','PaiController');
Route::resource('ciudades','CiudadeController');
Route::resource('pagos','PagosController');
Route::resource('demandas','DemandaController');
Route::resource('caracteristicas','CaracteristicaController');
Route::resource('reporte','ReporteController');
Route::resource('corredores','CorredoreController');
Route::resource('users','UsersController');



// GOOGLE MAPAS USO
//Route::get('/ciudades','CiudadesController@mapa');
//Route::get('/', function() { 
//	$config=array(); 
//	$config['center']='New York, USA';
//	GMaps::initialize($config); 
//	$ciudades=GMaps::create_map();                    
//    echo $ciudades['js'];
//	echo $ciudades['html']; 
//}); 

//Route::get('googlemap', 'CiudadesController@mapa');
//Route::get('googlemap/direction', 'MapController@direction');

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $fillable = [
        'id','nombre','','apellido','celular','telefono','ci',''
    ];
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use App\Cliente;
use Illuminate\Http\Request;
use Session;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clientes = Cliente::paginate(10);
        return view('clientes.index', compact('clientes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clientes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre' => 'required|max: 255',
            'apellido' => 'required|max: 255',
            'celular' => 'required',
            'telefono' => 'required',
            'ciudad_id'=>'nullable',
            'ci' => 'required'
           ]);

            Cliente::create($request->all());
            Session::flash('message','Cliente creado exitosamente');
            return redirect()->route('clientes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function show(Cliente $cliente)
    {   
        return view('clientes.show', compact('clientes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function edit(Cliente $cliente)
    {
       return view('clientes.edit', compact('clientes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cliente $cliente)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cliente $cliente)
    {
        $clientes->delete();

        Session::flash('message','Usuario eliminado exitosamente');
        return redirect('usuarios');
    }
}

resources/views/clientes/create.blade.php
@extends('layouts.admin')
@section('cont')
<body>
  <div class="container">
    <div class="panel-group mb-3">
      <div class="panel-heading" style="padding-bottom: 1vh;">
      </div>
      <div class="panel panel-success" style="padding: 1vh;border-radius: 9px;">
        <div class="form-group">
        @if($errors->any())
        <div class="alert alert-danger">
          <p style="color:green;">Formulario no completado! <br>Porfavor rellene todos los campos</p>
          <ul>
            @foreach($errors->all() as $error)
            <li>{{$error}}</li>
            @endforeach
          </ul>
        </div>
        @endif
          <form action="{{route('clientes.store')}}" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
            @csrf
            @if (session('status'))
            @csrf_filed()
            <div class="alert alert-success">
              {{ session('status') }}
            </div>
            @endif
            <div class="row">
              <div class="col-6"><span style="color:green;">Registro Clientes Pro Viviendas</span>
              <br>
              <br>
              <label>Nombre:</label>
              <input type="text" class="form-control" id="usr" name="nombre" data-msg="Por favor introduzca su nombre">
              <br>
              <label>Apellido:</label>
              <input type="text" class="form-control" name="apellido">
              <br>
              <div class="col">Género: <br>
                <input type="radio" name="gender" value="m" checked> Masculino
                <input type="radio" name="gender" value="f"> Femenino
                <input type="radio" name="gender" value="o"> Otro
              </div>
            </div>
            <div class="col-6">
              <br>
              <br><label>Celular:</label>
              <input type="text" class="form-control" name="celular">
              <br>
              <label for="usr">Telefono:</label>
              <input type="text" class="form-control" name="telefono">
              <br>
              <label>C.I:</label>
              <input type="text" class="form-control" name="ci">
              <br>
              <label>Imagen Cliente:</label>
              <br>
              <input name="img_perfil" type="file" />
              <div class="col-md-12 text-right">
                <button type="submit" class="btn btn-primary" onclick="return confirm('¿Desea guardar el registro?')">Guardar</button>
                <a href="{{route('clientes.index')}}" type="button" class="btn btn-outline-dark" style="cursor: grab;">Atras</a>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
</body>
@endsection

resources/views/clientes/edit.blade.php
@extends('layouts.layout')
@section('content')
<!DOCTYPE html>
<html lang="en">
  <body>
    <div class="container">
      <a href="{{route('clientes.index')}}" type="button" class="btn btn-outline-dark mb-3" style="cursor: grab;">Atras</a>
      <div class="panel-group mb-3"><div class="panel-heading" style="padding-bottom: 2vh;">Edicion Usuarios Pro Viviendas
      </div>
      <div class="panel panel-success" style="background: gainsboro; padding: 1vh;border-radius: 9px;">
        <div class="form-group">

          <form method="POST" accept-charset="utf-8" enctype="multipart/form-data">
            @csrf  <!-- token de proteccion -->
            @method('PUT')
            <label for="usr">Nombre:</label>
            <input type="text" class="form-control" id="usr" name="titulo">
            <br>
            <label for="usr">Apellido:</label>
            <input type="text" class="form-control" name="descripcion">
            <br>         
            <label for="usr">Celular:</label>
            <input type="text" class="form-control" name="direccion">
            <br>
            <label for="usr">Telefono:</label>
            <input type="text" class="form-control" name="lat">
            <br>
            <label for="usr">C.I:</label>
            <input type="text" class="form-control" name="lng">
           
            <label for="usr">Imagen Cliente:</label>
            <br>
            <input name="imagen" type="file" />
            <div class="col-md-12 text-right">
              <button type="submit" class="btn btn-primary" onclick="return confirm('¿Desea guardar el registro?')">Guardar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
@endsection

resources/views/clientes/index.blade.php
@extends('layouts.admin')
@section('cont')
<!DOCTYPE html>
<html lang="en">
  <body>
    <div class="card">
      <div class="container">
        <br>
         <h2 style="color:green;text-align: center;">Clientes</h2>
        <div class="card-header" style="text-align: left;"><a href="{{route('clientes.create')}}" type="button" class="btn btn-info mb-3" style=" cursor: grab;border-radius: 5px; border: 1px green solid;">Agregar Cliente</a>
          @if (Session::has('message'))
      <div class="alert alert-info" style="color: green;background-color: darkseagreen;">{{ Session::get('message') }}</div>
          @endif
        <form method="GET"  accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
          <div class="input-group">
            <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
            <span class="input-group-append">
              <button class="btn btn-secondary" type="submit">
              <i class="fa fa-search"></i>
              </button>
            </span>
          </div>
        </form></div>
        <div class="card-body">
          <table class="table table-striped">
            <thead class="tabla">
              <tr>
                <th scope="col">IdCliente</th>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">C.I</th>
                <th scope="col">Imagen</th>
                <th scope="col">Acciones</th>
              </tr>
            </thead>
            <tbody>
             @foreach($clientes as $cliente)
              <tr>
                <td>{{$cliente->id}}</a></td>
                <td>{{$cliente->nombre}}</td>
                <td>{{$cliente->apellido}}</td>
                <td>{{$cliente->ci}}</td>
                <td></td>
                <td>
              <!--VIEWS-->
                  <a title="View Image" href="{{ route('clientes.show',$cliente->id)}}"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i> View</button></a>

                   <!--EDITAR-->
                  <a title="Edit Image" href="{{ route('clientes.edit',$cliente->id)}}"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                 <!--DELETE-->
                  <form method="POST" accept-charset="UTF-8" style="display:inline"> 
                    <button href="{{ route('clientes.destroy',$cliente->id)}}" type="submit" class="btn btn-danger btn-sm" title="Delete Image" onclick="return confirm(&quot;¿Desea eliminar?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                  </form>
                 
                </td>
              </tr>
             @endforeach
            </tbody>
          </table>
          {{$clientes->links()}}
        </div>
      </div>
    </div>
  </body>
</html>
@endsection
<style type="text/css" media="screen">
.tabla{
color: green;
/* background-color: #212529; */
border-color: green;
}
</style>

resources/views/clientes/show.blade.php
@extends('layouts.layout')
@section('content')
<!DOCTYPE html>
<html lang="en">
  <body>
    <div class="container">
      <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">Img Inmueble
       <div class="card-body">
          <h5 class="card-title"></h5>
          <p class="card-text"></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"></li>
          <li class="list-group-item"></li>
          <li class="list-group-item"></li>
          <li class="list-group-item"></li>
          <li class="list-group-item"></li>
        </ul> 
        <div class="card-body">
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div> 
              
      </div>
    </div>
  </body>
</html>
@endsection