routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/inicio', function () {
  //  return view('layouts.menu');
//});


Route::get('/home/', 'HomeController@index')->name('home');
//USUARIOS CRUD
Route::get('/users/','UsersController@users')->name('users');
Route::get('/inmuebles/','InmuebleController@inmuebles')->name('inmuebles');
Route::get('/clientes/','ClienteController@clientes')->name('clientes');
Route::get('/demandas/','DemandaController@demandas')->name('demandas');
Route::get('/reportes/','ReporteController@demandas')->name('reportes');

//Nav-Bar
Route::resource('inmuebles','InmuebleController');
Route::resource('clientes','ClienteController');
Route::resource('pais','PaiController');
Route::resource('ciudades','CiudadeController');
Route::resource('pagos','PagosController');
Route::resource('demandas','DemandaController');
Route::resource('caracteristicas','CaracteristicaController');
Route::resource('reporte','ReporteController');
Route::resource('corredores','CorredoreController');
Route::resource('users','UsersController');



// GOOGLE MAPAS USO
//Route::get('/ciudades','CiudadesController@mapa');
//Route::get('/', function() { 
//	$config=array(); 
//	$config['center']='New York, USA';
//	GMaps::initialize($config); 
//	$ciudades=GMaps::create_map();                    
//    echo $ciudades['js'];
//	echo $ciudades['html']; 
//}); 

//Route::get('googlemap', 'CiudadesController@mapa');
//Route::get('googlemap/direction', 'MapController@direction');

app/Inmueble.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Inmueble extends Model
{
    protected $fillable = [
        'id', 'titulo','descripcion','oferta','tipo_inmueble','estado','direccion','lat','lng','precio','celular','telefono','whatsapp'
    ];
}

app/Http/Controllers/InmuebleController.php
<?php

namespace App\Http\Controllers;

use App\Inmueble;
use Illuminate\Http\Request;
use Session;

class InmuebleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $inmuebles = Inmueble::paginate(10);
        return view('inmuebles.index', compact('inmuebles'));kkkkkkkk
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('inmuebles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'titulo' => 'required|max: 255',
            'descripcion' => 'required|max: 255',
            'oferta' => 'required|in:venta,alquiler,anticretico',
            'tipo_inmueble' => 'required|in:casa,departamento,garzonier,lote',
            'estado' => 'required|in:disponible,vendido',
            'direccion' => 'required|max: 255',
            'lat' => 'required',
            'lng' => 'required',
            'precio' => 'required',
            'celular' => 'required',
            'telefono' => 'required',
            'whatsapp' => 'required'
        ]);

        //dd($request->all());
        Inmueble::create(
        ['titulo'=> $request->titulo,
        'descripcion'=> $request->descripcion,
        'oferta'=> $request->oferta,
        'tipo_inmueble'=> $request->tipo_inmueble,
        'estado'=> $request->estado,
        'direccion'=> $request->direccion,
        'lat'=> $request->lat,
        'lng'=> $request->lng,
        'precio'=> $request->precio,
        'celular'=> $request->celular,
        'telefono'=> $request->telefono,
        'whatsapp'=> $request->whatsapp,
        ]);

        Session::flash('message','Inmueble creado exisitosamente');
        return redirect()->route('inmuebles.index');  

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Inmueble  $inmueble
     * @return \Illuminate\Http\Response
     */
    public function show(Inmueble $inmueble)
    {   
        
        return view('inmuebles.show', compact('inmueble'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Inmueble  $inmueble
     * @return \Illuminate\Http\Response
     */
    public function edit(Inmueble $inmueble)
    {
        return view('inmuebles.edit', compact('inmueble'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Inmueble  $inmueble
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Inmueble $inmueble)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Inmueble  $inmueble
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id)
    {
        $inmueble = Inmueble::find($id);

        $inmueble->delete();

        Session::flash('message','Inmueble eliminado exitosamente');
        return redirect()->route('inmuebles.index');
    }

    public function inmuebles(){
       return view('inmuebles');
    }
}

resources/views/inmuebles/create.blade.php
@extends('layouts.admin')
@section('cont')
<div class="container">
  <div class="panel panel-success" style="padding: 1vh;border-radius: 9px;">
    <div class="form-group">
      <form action="{{route('inmuebles.store')}}" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
        @csrf  <!-- token de proteccion -->
        @if (session('status'))
        @csrf_filed()
        <div class="alert alert-success">
          {{ session('status') }}
        </div>
        @endif
        <div class="row">
          <div class="col-6"><span style="color:green;">Registro Inmueble Pro Viviendas</span>
          <br>
          <label>Titulo:</label>
          <input type="text" class="form-control" name="titulo" data-msg="Por favor introduzca un titulo">
          <br>
          
          <div class="form-group">Oferta
            <select name="oferta" id="oferta" class="form-control">
              <option >Elija una Oferta</option>
              <option value="venta">Venta</option>
              <option value="alquiler">Alquiler</option>
              <option value="anticretico">Anticretico</option>
            </select>
          </div>
          <div class="form-group">Tipo de Inmueble
            <select  name="tipo_inmueble" id="tipo_inmueble" class="form-control">
              <option >Elija tipo de Inmueble</option>
              <option value="casa">Casa</option>
              <option value="departamento">Departamento</option>
              <option value="garzonier">Garzonier</option>
              <option value="lote">Lote</option>
            </select>
          </div>
          <div class="form-group">Estado
            <select  name="estado" id="estado" class="form-control">
              <option >Elija un Estado</option>
              <option value="disponible">Disponible</option>
              <option value="vendido">Vendida</option>
            </select>
          </div>
          <label>Dirección:</label>
          <input type="text" class="form-control" name="direccion">
          <label for="usr">Descripción:</label>
          <textarea rows="4" cols="50" type="text" class="form-control" name="descripcion">
          </textarea>
        </div>
        <div class="col-6">
          <br>
          <label>Latitude:</label>
          <input type="text" class="form-control" name="lat">
          <br>
          <label>Longitude:</label>
          <input type="text" class="form-control" name="lng">
          
          <label>Precio:</label>
          <input type="text" class="form-control" name="precio">
          
          <label>Celular:</label>
          <input type="text" class="form-control" name="celular">
          <br>
          <label>Teléfono:</label>
          <input type="text" class="form-control" name="telefono">
          
          <label>Whatsapp:</label>
          <input type="text" class="form-control" name="whatsapp">
          <br>
          <label>Imagen Inmueble:</label>
          <br>
          <input name="imagen" type="file" />
          <div class="col-md-12 text-right">
            <button type="submit" class="btn btn-primary" onclick="return confirm('¿Desea guardar el registro?')">Guardar</button>
            <a href="{{route('inmuebles.index')}}" type="button" class="btn btn-outline-dark" style="cursor: grab;">Atras</a>
          </div>
        </div>
      </div>
    </form>
    
  </div>
</div>
</div>
</div>
@endsection

resources/views/inmuebles/edit.blade.php
@extends('layouts.admin')
@section('cont')
<!DOCTYPE html>
<html lang="en">
  <body>
    <div class="container">
      <a href="{{route('usuarios.index')}}" type="button" class="btn btn-outline-dark mb-3" style="cursor: grab;">Atras</a>
      <div class="panel-group mb-3"><div class="panel-heading">Edicion Usuarios Pro Viviendas
      </div>
      <div class="panel panel-success" style="background: gainsboro; padding: 1vh;border-radius: 9px;">
        <div class="form-group">

          <form action="{{route('inmuebles.update')}}" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
            @csrf  <!-- token de proteccion -->
            @method('PUT')
            <label for="usr">Titulo:</label>
            <input type="text" class="form-control" id="usr" name="titulo">
            <br>
            <label for="usr">Descripcion:</label>
            <input type="text" class="form-control" name="descripcion">
            <br>
            <div class="form-group">Oferta
              <select  name="tipo" id="tipo" type="text" class="form-control" name="oferta">
                <option >Elija una Oferta</option>
                <option value="venta">Venta</option>
                <option value="alquiler">Alquiler</option>
                <option value="anticretico">Anticretico</option>
              </select>
            </div>
             <div class="form-group">Tipo de Inmueble
              <select  name="tipo" id="tipo" type="text"  class="form-control" name="tipo_inmueble">
                <option >Elija tipo de Inmueble</option>
                <option value="casa">Casa</option>
                <option value="departamento">Departamento</option>
                <option value="garzonier">Garzonier</option>
                <option value="lote">Lote</option>
              </select>
            </div> 
            <div class="form-group">Estado
              <select  name="tipo" id="tipo" type="text"  class="form-control" name="estado">
                <option >Elija un Estado</option>
                <option value="disponible">Disponible</option>
                <option value="vendida">Vendida</option>
              </select>
            </div>           
            <label for="usr">Direccion:</label>
            <input type="text" class="form-control" name="direccion">
            <br>
            <label for="usr">Latitude:</label>
            <input type="text" class="form-control" name="lat">
            <br>
            <label for="usr">Longitude:</label>
            <input type="text" class="form-control" name="lng">
            <br>
            <label for="usr">Precio:</label>
            <input type="text" class="form-control" name="precio">
            <br>
            <label for="usr">Celular:</label>
            <input type="text" class="form-control" name="celular">
            <br>
            <label for="usr">Telefono:</label>
            <input type="text" class="form-control" name="telefono">
            <br>
            <label for="usr">Whatsapp:</label>
            <input type="text" class="form-control" name="whatsapp">
            <br>
            <label for="usr">Imagen Inmueble:</label>
            <br>
            <input name="imagen" type="file" />
            <div class="col-md-12 text-right">
              <button type="submit" class="btn btn-primary" onclick="return confirm('¿Desea guardar el registro?')">Guardar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
@endsection

resources/views/inmuebles/index.blade.php
@extends('layouts.admin')
@section('cont')
    <div class="card">
      <div class="container">
        <br>
        <h2 style="color:green;text-align: center;">Inmuebles</h2>
        <div class="card-header" style="text-align: left;"><a href="{{route('inmuebles.create')}}" type="button" class="btn btn-info mb-3" style=" cursor: grab;border-radius: 5px; border: 1px green solid;">Agregar Inmueble</a>
        <form method="GET"  accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
          <div class="input-group">
            <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
            <span class="input-group-append">
              <button class="btn btn-secondary" type="submit">
              <i class="fa fa-search"></i>
              </button>
            </span>
          </div>
        </form>
        @if (Session::has('message'))
        <div class="alert alert-info" style="color: green;background-color: darkseagreen;">{{ Session::get('message') }}</div>
        @endif
      </div>
      <div class="table-responsive-xl">
        <table class="table table-striped">
          <thead class="tabla">
            <tr>
              <th scope="col">IdInmueble</th>
              <th scope="col">Titulo</th>
              <th scope="col">Descripción</th>
              <th scope="col">Oferta</th>
              <th scope="col">Estado</th>
              <th scope="col">Dirección</th>
              <th scope="col">Precio</th>
              <th scope="col">Acciones</th>

            </tr>
          </thead>
          <tbody>
            @foreach($inmuebles as $inmueble)
            <tr>
              <td>{{$inmueble->id}}</td>
              <td>{{$inmueble->titulo}}</td>
              <td>{{$inmueble->descripcion}}</td>
              <td>{{$inmueble->oferta}}</td>
              <td>{{$inmueble->estado}}</td>
              <td>{{$inmueble->direccion}}</td>
              <td>{{$inmueble->precio}}</td>
              <td>
                <!--VIEWS-->
                <a title="View Image" href="{{ route('inmuebles.show',$inmueble->id ) }}"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i>Ver</button></a>
                <!--EDITAR-->
                <a title="Edit Image" href="{{ route('inmuebles.edit',$inmueble->id ) }}"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar</button></a>
                <!--DELETE-->
                <form method="POST" accept-charset="UTF-8" style="display:inline">
                  <button href="{{ route('inmuebles.destroy',$inmueble->id ) }}" type="submit" class="btn btn-danger btn-sm" title="Delete Image" onclick="return confirm(&quot;¿Desea eliminar?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Eliminar</button>
                </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
        {{$inmuebles->links()}}
        
      </div>
    </div>
  </div>
@endsection
<style type="text/css" media="screen">
.tabla{
color: green;
border-color: green;
}
</style>

resources/views/inmuebles/show.blade.php
@extends('layouts.admin')
@section('cont')
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<style>
/* Make the image fully responsive */
.carousel-inner img {
width: 50%;
height: 50%;
}
</style>
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card" style="width: 23rem;border: 2px solid green;border-radius: 5px;">
        <a href="{{route('inmuebles.index')}}" type="button" class="btn btn-outline-dark" style="cursor: grab;">Atras</a>
        
        <div id="demo" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          
          
          <!-- The slideshow -->
          <img src="..." class="card-img-top">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <h5 class="card-title">Titulo: {{$inmueble->titulo}}</h5>
              <p class="card-text"><li class="list-group-item">Tipo Inmueble: {{$inmueble->tipo_inmueble}}</li></p>
            </div>
          </div>
          <div class="card-body">
            
            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#demo" data-slide="prev">
              <span style="background-color: green;" class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo" data-slide="next">
              <span style="background-color: green;" class="carousel-control-next-icon"></span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="col">
      <ul class="list-group list-group-flush" style="border: 2px solid green;border-radius: 5px;">
        <li class="list-group-item">Id: {{$inmueble->id}}</li>
        <li class="list-group-item">Descripcion: {{$inmueble->descripcion}}</li>
        <li class="list-group-item">Oferta: {{$inmueble->oferta}}</li>
        <li class="list-group-item">Estado: {{$inmueble->estado}}</li>
        <li class="list-group-item">Direccion: {{$inmueble->direccion}}</li>
        <li class="list-group-item">latitude: {{$inmueble->lat}}</li>
        <li class="list-group-item">longitude: {{$inmueble->lng}}</li>
        <li class="list-group-item">Precio: {{$inmueble->precio}}</li>
        <li class="list-group-item">Celular: {{$inmueble->celular}}</li>
        <li class="list-group-item">Telefono: {{$inmueble->telefono}}</li>
        <li class="list-group-item">Whatsapp: {{$inmueble->whatsapp}}</li>
      </ul>
    </div>
  </div>
  
</div>
@endsection
<!-- <div class="card-body">
  <a href="#" class="card-link">Card link</a>
  <a href="#" class="card-link">Another link</a>
</div> -->