routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/inicio', function () {
  //  return view('layouts.menu');
//});


Route::get('/home/', 'HomeController@index')->name('home');
//USUARIOS CRUD
Route::get('/users/','UsersController@users')->name('users');
Route::get('/inmuebles/','InmuebleController@inmuebles')->name('inmuebles');
Route::get('/clientes/','ClienteController@clientes')->name('clientes');
Route::get('/demandas/','DemandaController@demandas')->name('demandas');
Route::get('/reportes/','ReporteController@demandas')->name('reportes');

//Nav-Bar
Route::resource('inmuebles','InmuebleController');
Route::resource('clientes','ClienteController');
Route::resource('pais','PaiController');
Route::resource('ciudades','CiudadeController');
Route::resource('pagos','PagosController');
Route::resource('demandas','DemandaController');
Route::resource('caracteristicas','CaracteristicaController');
Route::resource('reporte','ReporteController');
Route::resource('corredores','CorredoreController');
Route::resource('users','UsersController');



// GOOGLE MAPAS USO
//Route::get('/ciudades','CiudadesController@mapa');
//Route::get('/', function() { 
//	$config=array(); 
//	$config['center']='New York, USA';
//	GMaps::initialize($config); 
//	$ciudades=GMaps::create_map();                    
//    echo $ciudades['js'];
//	echo $ciudades['html']; 
//}); 

//Route::get('googlemap', 'CiudadesController@mapa');
//Route::get('googlemap/direction', 'MapController@direction');

app/Pai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pai extends Model
{
    protected $fillable = [
        'id', 'pais','descripcion'
    ];
}

app/Http/Controllers/PaiController.php
<?php

namespace App\Http\Controllers;

use App\Pai;
use Illuminate\Http\Request;
use Session;

class PaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $pais = Pai::paginate(5);
        return view('pais.index', compact('pais'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pais.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $request->validate([
            'pais' => 'required|in:bolivia',
            'descripcion' => 'required|max: 255'

        ]);

        //dd($request->all());

        Pai::create(
        ['pais'=> $request->pais,
        'descripcion'=> $request->descripcion,
        ]);

        Session::flash('message','Pais creado exisitosamente');
        return redirect()->route('pais.index'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pai  $pai
     * @return \Illuminate\Http\Response
     */
    public function show(Pai $pai)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pai  $pai
     * @return \Illuminate\Http\Response
     */
    public function edit(Pai $pai)
    {
        return view('pais.edit', compact('pais'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pai  $pai
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pai $pai)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pai  $pai
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pai $pai)
    {
        //
    }

    public function pais(){
       return view('pais');
    }
}

resources/views/Pais/create.blade.php
@extends('layouts.admin')
@section('cont')
<div class="container">
  <div class="panel panel-success" style="padding: 1vh;border-radius: 9px;">
    <div class="form-group">
      @if($errors->any())
        <div class="alert alert-danger">
          <p style="color:green;">Formulario no completado! <br>Porfavor rellene todos los campos</p>
          <ul>
            @foreach($errors->all() as $error)
            <li>{{$error}}</li>
            @endforeach
          </ul>
        </div>
        @endif
      <form action="{{route('pais.store')}}" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
        @csrf  <!-- token de proteccion -->
        @if (session('status'))
        @csrf_filed()
        <div class="alert alert-success">
          {{ session('status') }}
        </div>
        @endif
        <div class="row">
          <div class="col-6"><span style="color:green;">Registro Pais</span>
          <br>
          <div class="form-group">Pais
            <select  name="pais" id="pais" class="form-control">
              <option >Elija Pais</option>
              <option value="bolivia">Bolivia</option>
            </select>
          </div>
          <label for="usr">Descripción:</label>
          <textarea rows="4" cols="50" type="text" class="form-control" name="descripcion"></textarea>
        </div>
        <div class="col-6">
          <label>Imagen Ciudad:</label>
          <br>
          <input name="imagen" type="file" />
          <div class="col-md-12 text-right">
            <button type="submit" class="btn btn-primary" onclick="return confirm('¿Desea guardar el registro?')">Guardar</button>
            <a href="{{route('ciudades.index')}}" type="button" class="btn btn-outline-dark" style="cursor: grab;">Atras</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
</div>
</div>
@endsection

resources/views/Pais/edit.blade.php
@extends('layouts.admin')
@section('cont')
<div class="container">
  <div class="panel panel-success" style="padding: 1vh;border-radius: 9px;">
    <div class="form-group">
      <form action="{{route('pais.store')}}" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
        @csrf  <!-- token de proteccion -->
        @if (session('status'))
        @csrf_filed()
        <div class="alert alert-success">
          {{ session('status') }}
        </div>
        @endif
        <div class="row">
          <div class="col-6"><span style="color:green;">Registro Pais</span>
          <br>
          <div class="form-group">Pais
            <select  name="pais" id="pais" class="form-control">
              <option >Elija Pais</option>
              <option value="bolivia">Bolivia</option>
            </select>
          </div>
          <label for="usr">Descripción:</label>
          <textarea rows="4" cols="50" type="text" class="form-control" name="descripcion"></textarea>
        </div>
        <div class="col-6">
          <label>Imagen Ciudad:</label>
          <br>
          <input name="imagen" type="file" />
          <div class="col-md-12 text-right">
            <button type="submit" class="btn btn-primary" onclick="return confirm('¿Desea guardar el registro?')">Guardar</button>
            <a href="{{route('ciudades.index')}}" type="button" class="btn btn-outline-dark" style="cursor: grab;">Atras</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
</div>
</div>
@endsection

resources/views/Pais/index.blade.php
@extends('layouts.admin')
@section('cont')
<!--Google map-->
<!--Section: Contact v.2-->
<section class="section">
  <div class="card">
    
<div class="card">
      <div class="container">
        <br>
        <h2 style="color:green;text-align: center;">Pais</h2>
        <div class="card-header" style="text-align: left;"><a href="{{route('pais.create')}}" type="button" class="btn btn-info mb-3" style=" cursor: grab;border-radius: 5px; border: 1px green solid;">Agregar Pais</a>
        <form method="GET"  accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
          <div class="input-group">
            <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
            <span class="input-group-append">
              <button class="btn btn-secondary" type="submit">
              <i class="fa fa-search"></i>
              </button>
            </span>
          </div>
        </form>
        @if (Session::has('message'))
        <div class="alert alert-info" style="color: green;background-color: darkseagreen;">{{ Session::get('message') }}</div>
        @endif
      </div>
    <div class="table-responsive-xl">
        <table class="table table-striped">
          <thead class="tabla">
            <tr>
              <th scope="col">IdPais</th>
              <th scope="col">Pais</th>
              <th scope="col">Descripción</th>
              <th scope="col">Imagen</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>  
              @foreach($pais as $pai)     
            <tr>
              <td>{{$pai->id}}</td>
              <td>{{$pai->pais}}</td>
              <td>{{$pai->descripcion}}</td>
              <td></td>
              <td>
                <!--VIEWS-->
               
                <!--EDITAR-->
                <a title="Edit Image" href="{{ route('pais.edit',$pai->id ) }}"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar</button></a>
                <!--DELETE-->
                <form method="POST" accept-charset="UTF-8" style="display:inline">
                  <button  type="submit" class="btn btn-danger btn-sm" title="Delete Image" onclick="return confirm(&quot;¿Desea eliminar?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Eliminar</button>
                </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>        
       {{$pais->links()}}
      </div>
  </div>
</div>
<div class="card-body">
      <!--Google map-->
      <div id="map-container-google-9" class="z-depth-1-half map-container-7" >
        <iframe src="https://maps.google.com/maps?q=Miami&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0"
          style="border:0" allowfullscreen></iframe>
      </div>
    </div>
</div>
</section>
@endsection
<!--Section: Contact v.2-->
<style type="text/css" media="screen">
.map-container-7{
overflow:hidden;
padding-bottom:37.25%;
position:relative;
height:0;
}
.map-container-7 iframe{
left:0;
top:0;
height:100%;
width:100%;
position:absolute;
}
</style>